name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"] # Or "master" if that is your branch name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Inject API Key
        run: |
          sed -i "s/REPLACE_ME_WITH_KEY/${{ secrets.WEB3FORMS_ACCESS_KEY }}/g" index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .